ci(actions): fix yaml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -5,15 +5,12 @@ on: [push, pull_request]
 jobs:
   test:
     runs-on: ubuntu-latest
+    container:
+      image: raschidjfr/ionic-blank:ionic8-angular19-cypress14
 
     steps:
     - name: Checkout repository
-      uses: actions/checkout@v3
-
-    - name: Set up Node.js
-      uses: actions/setup-node@v3
-      with:
-        node-version: '20'
+      uses: actions/checkout@v4
 
     - name: Install dependencies
       run: npm ci
@@ -21,15 +18,14 @@ jobs:
     - name: Build project
       run: npm run build -- -c production
 
-    - name: Run tests in Docker
-      uses: docker://raschidjfr/ionic-blank:ionic8-angular19-cypress14
-      with:
-        args: bash -c "\
-          mkdir cypress \
-          && cp -r /github/workspace/cypress/* ./cypress \
-          && cp /github/workspace/cypress.config.ts . \
-          && cp -r /github/workspace/src/app/home/* ./src/app/home \
-          && npm i /github/workspace/dist/ionic-header-parallax-$(cd /github/workspace/dist/ionic-header-parallax && npm pkg get version).tgz \
-          && ng serve --host 0.0.0.0 --port 4200 \
-          & (wait-on http://0.0.0.0:4200 --timeout 30000 --interval 1000 && cypress run --headless) \
-          || { echo 'Angular server failed to start'; exit 1; }"
+    - name: Run tests
+      working-directory: /app
+      run: |
+          mkdir cypress
+          cp -r /cypress/* ./cypress
+          cp /cypress.config.ts .
+          cp -r /src/app/home/* ./src/app/home
+          npm i dist/ionic-header-parallax-$(cd dist/ionic-header-parallax && npm pkg get version).tgz
+          ng serve --host 0.0.0.0 --port 4200 &
+          (wait-on http://0.0.0.0:4200 --timeout 30000 --interval 1000 && cypress run --headless) \
+          || { echo 'Angular server failed to start'; exit 1; }
